name: liquid
version: 0.0.0
description: An implementation of the Liquid templating engine in Dart.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/dart_liquid
environment:
  sdk: ">=1.19.0"
dependencies:
  string_scanner: ^1.0.0
  source_span: ^1.0.0
dev_dependencies:
  expected_output: ^1.2.0
  test: ^0.12.0